config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  devise_for :users
  resources :users, only: [:show, :index]
  
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :username, presence: true, uniqueness: true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
  	devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :username, :age, :bio, :school, :work])
  	devise_parameter_sanitizer.permit(:account_update, keys: [:name, :username, :age, :bio, :school, :work])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:show]

  def show
  end

  def index
  	@users = User.all
  end

  private
  	def set_user
  		@user = User.find_by(username: params[:id])
  	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def bootstrap_class_for(flash_type)
		case flash_type
			when "success"
				"alert-success"
			when "error"
				"alert-danger"
			when "alert"
				"alert-warning"
			when "notice"
				"alert-info"
			else
				flash_type.to_s
		end
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "JBook", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
      
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "News Feed", "#" %></li>
        <li><%= link_to "Peeps", users_path %></li>

        <% if current_user %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= gravatar_tag current_user.email, size: 20 %> <%= current_user.username %><span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Profile", user_path(current_user.username) %></li>
            <li><%= link_to "Friends", "#" %></li>
            <li><%= link_to "Settings", edit_user_registration_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
      <% else %>
        <li><%= link_to "Log In", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JBook</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   	<%= render 'layouts/header' %>

   	<% flash.each do |type, message| %>
   		<div class="alert <%= bootstrap_class_for(type) %> fade-in">
   		<button class="close" data-dismiss="alert">X</button>
   		<%= message %>
   		</div>
   	<% end %>

    <%= yield %>
    
  </body>
</html>

app/views/users/index.html.erb
<div class="jumbotron text-center">
	<h2>Peeps!</h2>
	<div class="btn-group" role="group" aria-label="People Groups">
		<button type="button" class="btn btn-default">All</button>
		<button type="button" class="btn btn-default">My Friends</button>
		<button type="button" class="btn btn-default">Requests</button>
		<button type="button" class="btn btn-default">Pending</button>
	</div>

	<div class="container">
		<div class="row">
		<% @users.each do |user| %>
			<ul>
				<li><%= user.username %></li>
				<li><%= user.name %></li>
			</ul>
		<% end %>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<div class="jumbotron">
	<div class="container">
		<div class="row">
			<div class="col-md-4">
				<%= gravatar_tag current_user.email, size: 150 %>
			</div>
		</div>
	</div>
</div>

<div class="container">
	<div class="row">
		<div class="col-md-4">
			<h3><%= @user.username %></h3>
			<p>Name: <%= @user.name %></p>
			<p>Age: <%=@user.age %></p>
			<p>School: <%= @user.school %></p>
			<p>Work: <%= @user.work %></p>
		</div>
	</div>
</div>

<div class="container">
	<div class="row">
		<div class="col-md-4">
			<h3>About Me</h3>
			<small><%= @user.bio %></small>
		</div>
	</div>
</div>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>